# Use the Python image
FROM registry.redhat.io/ubi9/python-39@sha256:6f89c966a1939d3fcd8919f1e823f1794721e68fb3b31388230529ff622eebef

USER 0
ADD . .
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo12x.pt .
RUN chown -R 1001:0 ./ && \
    yum install -y mesa-libGL && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    chmod 644 yolo12x.pt && \
    chmod 775 uploads && \
    chmod 775 runs && \
    chmod 775 runs/detect

USER 1001

RUN pip install -r requirements.txt

# Run the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
